### ISSUE TITLE
Generate Brainhack 2019 website

### ISSUE THREAD

**Issue by meneguzzi** [brainhack-poa/brainhack-poa.github.io#1]
Do not clone the repo for 2018, create a new repo and populate it with the material from the 2018 repo (there's a reason for that)

**Comment by nathaliaesper** [comment]
Repositório criado para o brainhack 2019. Site já está no ar, porém com as informações de 2018 ainda.

**Comment by nathaliaesper** [comment]
closes #1

**Comment by meneguzzi** [comment]
Excelente, muito obrigado!

**Comment by meneguzzi** [comment]
Editei o index.html do domínio principal para redirecionar para 2019.

**Comment by meneguzzi** [comment]
Acho que tá feito isto.
